# This gives us full control over what we intend to do
# in the job
language: minimal
# Needed for docker
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
script:
  - make build-deb DEB_PACKAGE_DESCRIPTION="Logrus Demo" DEB_PACKAGE_NAME=demo BINARY_NAME=demo && ls ./artifacts/
deploy:
  provider: packagecloud
  repository: logrus-demo 
  username: amitsaha
  token: "${PACKAGECLOUD_TOKEN}"
  dist: "ubuntu/xenial"   
  local-dir: "./artifacts"
  package_glob: "*.deb"
  skip_cleanup: true
  on:
    branch: master
