FROM golang:1.10
ENV PACKAGE_PATH $GOPATH/src/git.host/mypackage
RUN mkdir -p  $PACKAGE_PATH
COPY . $PACKAGE_PATH
WORKDIR $PACKAGE_PATH
ARG version_string
ARG binary_name
ENV BINARY_NAME $binary_name
RUN make build && cp ${binary_name} /${binary_name}
ENTRYPOINT "/${binary_name}"
